#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

cp system/Fluid/decomposeParDict system/decomposeParDict

runApplication decomposePar -region Fluid

runParallel "$(getApplication)"

runApplication reconstructPar -region Fluid

#------------------------------------------------------------------------------
